name: Create Jira Card from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create a new Jira issue
      run: |
        curl -X POST -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
        --header "Content-Type: application/json" \
        --data '{"fields": {"project": {"key": "ARKAMA"},"summary": "${{ github.event.issue.title }}","description": "${{ github.event.issue.body }}","issuetype": {"name": "Task"}}}' \
        https://arkama.atlassian.net//rest/api/2/issue/
      env:
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
