name: Example Workflow

on:
  push:
    branches:
      - master
  issues:
    types: [opened]
jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Show repo env secret
        run: |
          echo ${{ secrets.JIRA_ACCOUNT }}
