name: Create Jira Card from GitHub Issue

on:
  issues:
    types: [opened]
jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Set GitHub Issue URL
      id: set_issue_url
      env:
       JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
       JIRA_TOKEN_API: ${{ secrets.JIRA_TOKEN_API }}
      run: echo ${{ secrets.JIRA_ACCOUNT }}
