name: Check and Create Jira Card

on:
  issues:
    types: [opened]

jobs:
  check_and_create_card:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set GitHub Issue URL
      id: set_issue_url
      run: |
        ISSUE_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
        echo "Issue URL: $ISSUE_URL"
        echo "ISSUE_URL=$ISSUE_URL" >> $GITHUB_ENV

    - name: Check if Jira card exists
      id: check_jira_card
      run: |
        JIRA_URL="https://arkama.atlassian.net"
        SEARCH_URL="$JIRA_URL/rest/api/3/search?jql=Github%3D%22${{ env.ISSUE_URL }}%22"
        JIRA_USERNAME=${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}

        # Fetching the Jira search result
        RESPONSE=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
          -X GET \
          -H "Content-Type: application/json" \
          "$SEARCH_URL")

        # Debug: Print the entire response
        echo "Response: $RESPONSE"
        
        # Extract the total number of issues found
        TOTAL=$(echo $RESPONSE | jq '.total')

        echo "Total issues found: $TOTAL"
        echo "TOTAL=$TOTAL" >> $GITHUB_ENV

    - name: Create Jira card if none exists
      if: env.TOTAL == '0'
      run: |
        JIRA_URL="https://arkama.atlassian.net"
        JIRA_PROJECT_KEY="YOUR_PROJECT_KEY"
        ISSUE_SUMMARY="GitHub Issue #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
        ISSUE_DESCRIPTION="Link: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"

        # Create a new Jira card
        curl -X POST -u $JIRA_USERNAME:$JIRA_API_TOKEN \
         --header "Content-Type: application/json" \
         --data '{"fields": {"project": {"key": "'"$JIRA_PROJECT_KEY"'"},\
                "issuetype": {"name": "Task"}},\
               "summary": "'"${ISSUE_SUMMARY}"'",\
               "description": "'"${ISSUE_DESCRIPTION}"'",\
               "customfield_10065": { "name": "Label","value": "'"${{ github.event.issue.labels[0].name }}"'"},\
               "customfield_10071" : "'"${{ env.ISSUE_URL }}"'"}'\
          "$JIRA_URL/rest/api/3/issue"
