name: Create Jira Card from GitHub Issue

on:
  issues:
    types: [opened]
jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:

    ###########################################################################

    - name: Set GitHub Issue URL
      id: set_issue_url
      env:
       JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
       JIRA_TOKEN_API: ${{ secrets.JIRA_TOKEN_API }}
      #run: echo ${{ secrets.JIRA_ACCOUNT }}
      run: |
        ISSUE_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
        echo "Issue URL: $ISSUE_URL"
        echo "ISSUE_URL=$ISSUE_URL" >> $GITHUB_ENV
        echo "JIRA_EMAIL=${{ secrets.JIRA_ACCOUNT }}" >> $GITHUB_ENV
        echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}" >> $GITHUB_ENV

    ###########################################################################
    
    - name: Check if Jira card exists
      id: check_jira_card
      run: |
        JIRA_URL="https://arkama.atlassian.net"
        SEARCH_URL="$JIRA_URL/rest/api/3/search?jql=Github%3D%22${{ env.ISSUE_URL }}%22"
        
        # Debug
        #echo ${{ env.ISSUE_URL }}
        #echo ${{ env.JIRA_EMAIL }}
        #echo ${{ env.JIRA_API_TOKEN }}

        # Fetching the Jira search result
        RESPONSE=$(curl -X POST -u ${{ env.JIRA_EMAIL }}:${{ env.JIRA_API_TOKEN }} \
          -X GET \
          -H "Content-Type: application/json" \
          "$SEARCH_URL")

        # Debug: Print the entire response
        echo "Response: $RESPONSE"
        
        # Extract the total number of issues found
        TOTAL=$(echo $RESPONSE | jq '.total')

        echo "Total issues found: $TOTAL"
        echo "TOTAL=$TOTAL" >> $GITHUB_ENV

    ###########################################################################

    - name: Create Jira card if none exists
      if: env.TOTAL == '0'
      run: |
        JIRA_URL="https://arkama.atlassian.net"
        JIRA_PROJECT_KEY="ARKAMA"
        ISSUE_TYPE="Task"
        ISSUE_SUMMARY="${{ github.event.issue.title }}"
        ISSUE_BODY="${{ github.event.issue.body }}"
        ISSUE_URL="https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
        ISSUE_LABEL="${{ github.event.issue.labels[0].name }}"
        ISSUE_LABEL="${ISSUE_LABEL:-feature}"
        ESCAPED_BODY=$(echo "${ISSUE_BODY}" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\n/\\n/g; s/\r/\\r/g; s/\t/\\t/g; s/`/\\`/g; s/´/\\´/g; s/'"'/\\'"'/g')

        # Create a new Jira card
         curl -X POST -u ${{ env.JIRA_EMAIL }}:${{ env.JIRA_API_TOKEN }} \
         --header "Content-Type: application/json" \
         --data '{"fields": { "project": {"key": "ARKAMA"},"issuetype": {"name": "'"${ISSUE_TYPE}"'"},"summary": "'"${ISSUE_SUMMARY}"'","description": "'"${ESCAPED_BODY}"'","customfield_10071" : "'"${ISSUE_URL}"'","customfield_10065": {"name": "Label","value": "'"${ISSUE_LABEL}"'"}}}'\
         "$JIRA_URL/rest/api/2/issue"
